"""SQLAlchemy ORM models for the Utopia cognitive architecture.

Import all model modules here so that Base.metadata is fully populated.
"""

from utopia.models.core import Operator, Device
from utopia.models.integration import OAuthConnection, Permission, WebhookReceipt
from utopia.models.vector_ctrl import (
    AntiGoal,
    LifeArc,
    Mission,
    Season,
    Thread,
    ThreadConstraint,
)
from utopia.models.evidence import (
    BehaviorEvent,
    ContextSnapshot,
    DerivedFeature,
    SubjectiveCheckin,
)
from utopia.models.execution import (
    BlockerEstimate,
    PolicyDecision,
    ReentryArtifact,
    StateEstimate,
    Trace,
)
from utopia.models.physiology import (
    BiomarkerPanel,
    PhysiologyFeature,
    WhoopBodyMeasurement,
    WhoopConnection,
    WhoopCycle,
    WhoopRecovery,
    WhoopSleep,
    WhoopWorkout,
)
from utopia.models.aether import (
    Case,
    Concept,
    DiagnosticQuestion,
    Edge,
    Extraction,
    FailureMode,
    Heuristic,
    LensPack,
    LensPackItem,
    Mechanism,
    Pattern,
    Protocol,
    Rule,
    Source,
    SourceChunk,
    Tradeoff,
)
from utopia.models.reasoning import (
    ContradictionReport,
    DecisionBrief,
    Interrogation,
    OptionPath,
    Problem,
    ProblemStructure,
)
from utopia.models.review import (
    CalibrationRecord,
    Closure,
    PatternUpdate,
    ReviewSession,
    RulePromotion,
)

__all__ = [
    "Operator",
    "Device",
    "OAuthConnection",
    "Permission",
    "WebhookReceipt",
    "LifeArc",
    "Season",
    "Mission",
    "Thread",
    "ThreadConstraint",
    "AntiGoal",
    "SubjectiveCheckin",
    "BehaviorEvent",
    "ContextSnapshot",
    "DerivedFeature",
    "StateEstimate",
    "BlockerEstimate",
    "ReentryArtifact",
    "PolicyDecision",
    "Trace",
    "WhoopConnection",
    "WhoopBodyMeasurement",
    "WhoopCycle",
    "WhoopSleep",
    "WhoopRecovery",
    "WhoopWorkout",
    "PhysiologyFeature",
    "BiomarkerPanel",
    "Source",
    "SourceChunk",
    "Extraction",
    "Concept",
    "Mechanism",
    "Tradeoff",
    "FailureMode",
    "Heuristic",
    "DiagnosticQuestion",
    "Protocol",
    "LensPack",
    "LensPackItem",
    "Case",
    "Rule",
    "Pattern",
    "Edge",
    "Problem",
    "ProblemStructure",
    "Interrogation",
    "DecisionBrief",
    "OptionPath",
    "ContradictionReport",
    "Closure",
    "ReviewSession",
    "RulePromotion",
    "PatternUpdate",
    "CalibrationRecord",
]
