"""reasoning ORM models — problem structurer and decision artifacts.

The Reasoning layer is the Problem Room: raw prompt → structured problem
→ interrogations → decision brief → option paths → contradiction reports.

M009 also activates the deferred FK from execution.policy_decisions.problem_id
to reasoning.problems.id (applied in the migration, reflected here as a
relationship on PolicyDecision if needed).

Matches: Utopia Formal Architecture DB etc.md section 14.
"""

import datetime
import decimal
import uuid

from sqlalchemy import DateTime, ForeignKey, Integer, Numeric, Text, text
from sqlalchemy.dialects.postgresql import ARRAY, JSONB
from sqlalchemy.orm import Mapped, mapped_column

from utopia.db import Base


class Problem(Base):
    """A structured problem submitted for reasoning.

    The raw_prompt is the operator's unstructured input. Everything else
    is produced by the Problem Structurer and downstream reasoning modules.
    """

    __tablename__ = "problems"
    __table_args__ = {"schema": "reasoning"}

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True)
    operator_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("core.operators.id"), nullable=False
    )
    title: Mapped[str] = mapped_column(Text, nullable=False)
    raw_prompt: Mapped[str] = mapped_column(Text, nullable=False)
    problem_kind: Mapped[str | None] = mapped_column(Text, nullable=True)
    urgency_score: Mapped[decimal.Decimal | None] = mapped_column(
        Numeric(6, 3), nullable=True
    )
    stakes_score: Mapped[decimal.Decimal | None] = mapped_column(
        Numeric(6, 3), nullable=True
    )
    uncertainty_score: Mapped[decimal.Decimal | None] = mapped_column(
        Numeric(6, 3), nullable=True
    )
    state_at_creation: Mapped[str | None] = mapped_column(Text, nullable=True)
    thread_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("vector_ctrl.threads.id"), nullable=True
    )
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )


class ProblemStructure(Base):
    """Structured decomposition of a problem produced by the Problem Structurer."""

    __tablename__ = "problem_structures"
    __table_args__ = {"schema": "reasoning"}

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True)
    problem_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("reasoning.problems.id"), nullable=False
    )
    objective: Mapped[str | None] = mapped_column(Text, nullable=True)
    stakes: Mapped[str | None] = mapped_column(Text, nullable=True)
    actors: Mapped[list] = mapped_column(JSONB, nullable=False, server_default="[]")
    incentives: Mapped[list] = mapped_column(JSONB, nullable=False, server_default="[]")
    constraints: Mapped[list] = mapped_column(JSONB, nullable=False, server_default="[]")
    assumptions: Mapped[list] = mapped_column(JSONB, nullable=False, server_default="[]")
    unknowns: Mapped[list] = mapped_column(JSONB, nullable=False, server_default="[]")
    irreversibilities: Mapped[list] = mapped_column(JSONB, nullable=False, server_default="[]")
    bottlenecks: Mapped[list] = mapped_column(JSONB, nullable=False, server_default="[]")
    observable_facts: Mapped[list] = mapped_column(JSONB, nullable=False, server_default="[]")
    narrative_layer: Mapped[list] = mapped_column(JSONB, nullable=False, server_default="[]")
    distortion_candidates: Mapped[list] = mapped_column(JSONB, nullable=False, server_default="[]")
    confidence: Mapped[decimal.Decimal | None] = mapped_column(Numeric(5, 4), nullable=True)
    generated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )


class Interrogation(Base):
    """A set of high-leverage questions generated by the Interrogator."""

    __tablename__ = "interrogations"
    __table_args__ = {"schema": "reasoning"}

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True)
    problem_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("reasoning.problems.id"), nullable=False
    )
    interrogation_kind: Mapped[str] = mapped_column(Text, nullable=False)
    questions: Mapped[list] = mapped_column(JSONB, nullable=False)
    rationale: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    generated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )


class DecisionBrief(Base):
    """A synthesized decision brief for a problem."""

    __tablename__ = "decision_briefs"
    __table_args__ = {"schema": "reasoning"}

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True)
    problem_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("reasoning.problems.id"), nullable=False
    )
    classification: Mapped[str | None] = mapped_column(Text, nullable=True)
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    key_unknowns: Mapped[list] = mapped_column(JSONB, nullable=False, server_default="[]")
    blind_spots: Mapped[list] = mapped_column(JSONB, nullable=False, server_default="[]")
    risks: Mapped[list] = mapped_column(JSONB, nullable=False, server_default="[]")
    relevant_lens_pack_ids: Mapped[list] = mapped_column(
        ARRAY(JSONB), nullable=False, server_default="{}"
    )
    recommendation_summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    confidence: Mapped[decimal.Decimal | None] = mapped_column(Numeric(5, 4), nullable=True)
    generated_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )


class OptionPath(Base):
    """A concrete strategic option within a decision brief."""

    __tablename__ = "option_paths"
    __table_args__ = {"schema": "reasoning"}

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True)
    decision_brief_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("reasoning.decision_briefs.id"), nullable=False
    )
    option_label: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    expected_upside: Mapped[str | None] = mapped_column(Text, nullable=True)
    expected_downside: Mapped[str | None] = mapped_column(Text, nullable=True)
    reversibility: Mapped[str | None] = mapped_column(Text, nullable=True)
    risk_score: Mapped[decimal.Decimal | None] = mapped_column(Numeric(6, 3), nullable=True)
    recommendation_rank: Mapped[int | None] = mapped_column(Integer, nullable=True)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )


class ContradictionReport(Base):
    """A detected contradiction between the operator's narrative and evidence.

    Contradiction kinds: narrative_vs_behavior, physiology_vs_claim,
    vector_vs_action.
    """

    __tablename__ = "contradiction_reports"
    __table_args__ = {"schema": "reasoning"}

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True)
    operator_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("core.operators.id"), nullable=False
    )
    problem_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("reasoning.problems.id"), nullable=True
    )
    contradiction_kind: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    evidence: Mapped[list] = mapped_column(JSONB, nullable=False, server_default="[]")
    severity: Mapped[decimal.Decimal | None] = mapped_column(Numeric(6, 3), nullable=True)
    created_at: Mapped[datetime.datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
